// <auto-generated />
namespace GPOrder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FilesToShopPictures3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FilesToShopPictures3));
        
        string IMigrationMetadata.Id
        {
            get { return "201703241416039_FilesToShopPictures3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
